spring:
  application:
    name: msclient

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/msclient?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Africa/Douala&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    #  Adresse du broker Kafka auquel l'application se connecte
    bootstrap-servers: localhost:9092

    producer:
      # il faut savoir que les messages dans kafka sont des chaines de caractère,
      # donc il faut pouvoir sérialiser nos objet pour les transportés sur KAFKA
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Ici, on précise de mettre les types dans le headers (il s'agit du type d'evenement
        # exple : __TypeId__ = com.msclient.event.ClientCreatedEvent
        #spring.json.add.type.headers: true
        #spring.json.type.mapping: clientCreated:com.msclient.event.ClientCreatedEvent
        acks: all
        retries: 3



kafka:
  topics:
    clients: client.created

server:
  port: 8003

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:8761/eureka/

  instance:
    prefer-ip-address: true
    appname: msclient
    instanceId: msclient:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html